---
title: "Deprivation"
author: "Jon Minton"
date: "28/09/2021"
output: html_document
---

# Key points

## Deprivation: key points 

*The SIMD is the Scottish Government's official tool for identifying small area concentrations of multiple deprivation across all of Scotland. The SIMD provides a relative ranking of 6,976 small areas (datazones) across Scotland from the most deprived (ranked one) to the least deprived in Scotland (ranked 6,976).  Direct comparisons of indicators between all releases are not possible because of changes to datazone boundaries.*

The main measure of deprivation used in Scotland is the Scottish Index of Multiple Deprivation (SIMD).  The SIMD was first published by the Scottish Government in 2004. Successive revisions were published in 2004, 2006, 2009, 2012, 2016 and 2020, which is the most recent version of the index.

The following points are summarised from the results of the most recent (2020) version of the [Scottish Index of Multiple Deprivation (SIMD)](https://www.gov.scot/collections/scottish-index-of-multiple-deprivation-2020/).  

[Key findings reported for SIMD 2020](https://www.scotpho.org.uk/(Background%20note:%20The%20SIMD%20is%20the%20Scottish%20Government's%20official%20tool%20for%20identifying%20small%20area%20concentrations%20of%20multiple%20deprivation%20across%20all%20of%20Scotland.%20The%20SIMD%20provides%20a%20relative%20ranking%20of%206,976%20small%20areas%20(datazones)%20across%20Scotland%20from%20the%20most%20deprived%20(ranked%20one)%20to%20the%20least%20deprived%20in%20Scotland%20(ranked%206,976).%C2%A0%20The%20Scottish%20Government%20have%20published%20previous%20indices%20of%20multiple%20deprivation%20in%202004,%202006,%202009,%202012,%20and%202016.%C2%A0%20However%20direct%20comparisons%20of%20indicators%20between%20all%20releases%C2%A0are%20not%20possible%20because%20of%20changes%20to%20datazone%20boundaries.)) include: 

- **Deprivation in Highlands and Islands**: None of the 15% most deprived areas of Scotland are in Shetland, Orkney or the Western Isles
- **Persistent Deprivation**: Fourteen small areas have remained in the 5% most deprived places in Scotland since the first SIMD release in 2004. Nine of these are in Glasgow City.  
- **Council areas in the Central Belt**: Glasgow City and Edinburgh council areas have both experienced substantial (2% or more) falls in deprivation scores from SIMD 2016 to SIMD 2020, whereas most neighbouring council areas along the Central Belt have experienced substantial (2% or more) increases in deprivation scores over the same period. 

# Introduction

## Deprivation: Introduction

The Scottish Index of Multiple Deprivation (SIMD) is a measure of area deprivation, not individual or household level deprivation; affluent households may live in deprived areas and vice versa. The overall SIMD score and deprivation ranking for small areas (known as datazones) is a weighted average of area-based scores from seven domains, each comprised of a number of indicators. In total, more than 30 separate indicators are included in the overall SIMD score. 

## Spatial scales, domains and indicators

The SIMD  is available at [datazone](http://www.scotland.gov.uk/library5/society/snsg-02.asp) level as an overall deprivation index, and as separate indices for different domains. The SIMD 2020 summarises 34 indicators nested within the following seven domains:

- Income
- Employment
- Education
- Health
- Access to Services
- Crime
- Housing


## History

The publication of the [Independent Inquiry into Inequalities in Health Report]() in 1998 gave a new impetus to the study of the relationship between poverty and health. In the years following its publication, alternatives to social class - as a general measure of relative affluence or poverty in a society - were increasingly investigated such as unemployment and single parenthood. Several different ways of combining variables taken from the census or elsewhere were developed as a means of categorising deprivation within the populations of small geographically defined areas (census enumeration districts, local government wards, or postcode sectors). The methods in most common use until recently were those developed by Townsend et al, Jarman and Carstairs and Morris. All use methods of combining variables to generate a summary score to reflect the socioeconomic status of a locality relative to the distribution of scores obtained for all localities. For more information on the relative merits of these particular measures see ['Which deprivation? A comparison of selected deprivation indexes'](http://jpubhealth.oxfordjournals.org/cgi/content/abstract/13/4/318?ijkey=e017f6510f37ea6bf87ac17d1d0be2c13f1ec783&keytype2=tf_ipsecsha).

The SIMD was first published in June 2004, based on a slightly earlier initiative from England & Wales. In 2000, as part of the [Neighbourhood Statistics programme](https://digitalblog.ons.gov.uk/2017/04/19/goodbye-to-old-friends-and-hello-to-the-new/) in England and Wales, a project to create a new [Index of Multiple Deprivation for England](https://www.gov.uk/government/collections/english-indices-of-deprivation) was commissioned. In Scotland, as part of the Scottish Executive's Scottish Neighbourhood Statistics initiative, a new [Scottish Index of Multiple Deprivation (SIMD)](http://www.scotland.gov.uk/simd) using similar methodology was published in June 2004 and was updated in 2006, 2009, 2012, 2016 and 2020. The English index combined information relating to income, employment, education, health, skills and training, barriers to housing and services and crime into an overall measure of deprivation at a small area level. One of the key differences between this type of index and previous deprivation measures is that it is derived from administrative data and, because it is not reliant on Census data, can be updated on a more frequent basis.  English indices of deprivation were subsequently published for 2004, 2007, 2015 and 2019.

## Value of measuring area deprivation

The importance of deprivation as a key component of social inequality has been recognised for a long time. It is widely accepted that deprivation increases the risk of early death and is associated with higher rates of illness from certain diseases. For example, in 2013-2014, [healthy life expectancy](http://www.gov.scot/Publications/2015/10/6061/5) for those living in the 10% most deprived areas was 25.1 years lower for males and 22.1 years lower for females compared to those living in the 10% least deprived areas.

In relation to health, measures of deprivation are used for a variety of purposes, including: measuring and monitoring inequalities in health, access to healthcare and healthcare activity; and for standardising health and healthcare activity measures to enable more meaningful comparisons between organisations or geographical areas.

There are clearly many links between deprivation and health inequalities. The section on [health inequalities](https://www.scotpho.org.uk/comparative-health/health-inequalities/policy-context) summarises the Scottish Government's approach to tackling health inequalities, which focuses on alleviating deprivation and its impact on health. The data pages of this section provide a selection of charts highlighting associations between health and deprivation, while the key data sources section describes useful sources of deprivation data.

The SIMD is widely used across local and national government for directing resources, setting targets ([Scotland Performs](http://www.scotland.gov.uk/About/scotPerforms)) and monitoring social and health inequalities (see for example [Long-Term Monitoring of Health Inequalities: Headline Indicators](http://www.gov.scot/Publications/2015/10/6061)).


## Recommended uses for the SIMD

The [SIMD 2020 Introduction document](https://www.gov.scot/binaries/content/documents/govscot/publications/statistics/2020/01/scottish-index-multiple-deprivation-2020/documents/scottish-index-multiple-deprivation-2020/scottish-index-multiple-deprivation-2020/govscot%3Adocument/scottish-index-multiple-deprivation-2020.pdf?forceDownload=true) recommends use of the SIMD for the following purposes:

- Comparing small areas in terms of overall and domain-specific scores
- Comparing small areas within council
- Identifying areas where people experience multiple forms of deprivation, and areas of greater need for support and intervention

The same Introduction recommends **against** attempting to use the SIMD for the following purposes: 

- Comparing areas by rank rather than score; 
- Comparing ranks over time; 
- Comparing SIMD scores and ranks based on the SIMD against scores based on the English/Welsh IMD (as they are calculated differently); 
- Attempting to infer where rich and poor households live; 
- and: Identifying affluent areas (as absence of deprivation is not the same as presence of affluence). 


# Policy context

## Deprivation: policy context

Tackling deprivation has been a government priority in Scotland over a long period. In 1988 the Scottish Office launched its New Life for Urban Scotland Initiative which created regeneration partnerships in four peripheral housing estates: Castlemilk in Glasgow, Ferguslie Park in Paisley, Wester Hailes in Edinburgh and Whitfield in Dundee.

After devolution in 1999, the then Scottish Executive committed itself to tackling poverty and disadvantage through its Social Justice Strategy. The Social Justice Strategy was supported nationally by the Social Justice milestones and locally by the establishment of 'Social Inclusion Partnerships (SIPs)' throughout Scotland (replacing what were formerly Priority Partnership Areas (PPAs) and Regeneration Partnerships (RPs). A key feature of these initiatives was their focus on regeneration and social inclusion in areas of high deprivation.

In November 2008, the Scottish Government launched [Achieving Our Potential: A Framework to Tackle Poverty and Income Inequality in Scotland, 2008](http://www.gov.scot/Publications/2008/11/20103815/0), which outlined a long-term approach to reducing levels of poverty and income inequality in Scotland. Among its key aims are:

- to increase overall income and the proportion of income earned by the three lowest income deciles by 2017;
- to decrease the proportion of individuals living in poverty; and
- to increase [healthy life expectancy](https://www.scotpho.org.uk/population-dynamics/healthy-life-expectancy/key-points) at birth in the most deprived areas.

Related to this, many of the health-related indicators set out in [Scotland Performs](https://nationalperformance.gov.scot/) (for example, on smoking, problem drug misuse and alcohol-related admissions to hospital) will particularly benefit people living in the most deprived communities in Scotland if their targets are achieved.

A report from the Independent Advisor on Poverty and Inequality to the First Minister, [Shifting the Curve](http://www.gov.scot/Publications/2016/01/1984), was published in January 2016. The latest report on [Long Term Monitoring of Health Inequalities](http://www.gov.scot/Publications/2017/12/4517) was published in December 2017.

The international context is set by the World Health Organization [Commission on Social Determinants of Health (2008)](http://whqlibdoc.who.int/publications/2008/9789241563703_eng.pdf), which notes that:

the development of a society, rich or poor, can be judged by the quality of its population's health, how fairly health is distributed across the social spectrum, and the degree of protection provided from disadvantage as a result of ill-health. 

In 2010, the Chair of the Commission, Sir Michael Marmot, concluded a strategic review of health inequalities in England ([Strategic Review of Health Inequalities in England Post 2010](http://www.instituteofhealthequity.org/)).  Its analysis and recommendations remain relevant to Scotland.

In 2017 the Scottish parliament passed the [Child Poverty (Scotland) Act 2017](https://www.jrf.org.uk/report/poverty-scotland-2018). This is an Act of the Scottish Parliament to set targets relating to the eradication of child poverty; to make provision about plans and reports relating to the targets; and to establish the Poverty and Inequality Commission and provide for its functions.

All of the above illustrate the importance of deprivation within past and current government policy.

In 2018, the Joseph Rowntree Foundation published [Poverty in Scotland](https://www.jrf.org.uk/report/poverty-scotland-2018), looking at poverty trends for families with children in Scotland. And in 2017, [UK Poverty 2017](https://www.jrf.org.uk/report/uk-poverty-2017) a report assessing the progress made in reducing poverty and tackling the underlying drivers of poverty.


## Uses of SIMD in resource allocation

The [NHS Scotland Resource Allocation Committee (NRAC)](http://www.tagra.scot.nhs.uk/research/) was established to ensure the Arbuthnott Formula (2000-2005) was still allocating resources to NHS Boards in a way that reflects local need for healthcare. The Arbuthnott formula included a Morbidity and Life Circumstances adjustment for deprivation. NRAC's 2007 report recommended (and it was accepted by Government) that in future there should be separate "additional needs" adjustments for different care groups. It did not recommend using SIMD as part of the revised Formula, since the SIMD indicators did not appear to be the best predictors of healthcare need. However, 30% of NHS Scotland funding (e.g. for dental practices in deprived areas) is allocated using the SIMD.


# Data

## Deprivation: data

Deprivation profiles, which provide data on health outcomes and determinants for each SIMD 2012 quintile (1=most deprived, 5=least least), for all health boards and local authorities within Scotland, are available in the [profiles pages]().

In addition, deprivation related tables and graphs appear throughout this site within topic pages e.g. physical activity, deaths, etc. For further information on how deprivation is related to a specific topic, please go to the data section for that topic.  

Deprivation related tables and graphs appear throughout this site within topic pages e.g. physical activity, deaths, etc. For further information on how deprivation is related to a specific topic, please go to the data section for that topic.

Chart 1 shows the how the 15% most deprived datazones in Scotland are distributed across the 32 local authorities. Glasgow City contains nearly a third (30.6%) of the 15% most deprived datazones. Four local authorities (Eilean Siar, Moray, Orkney Islands and Shetland Islands) have none of their population living in the 15% most deprived datazones.


Chart 2 shows the proportion of the datazones within each local authority that are within the 15% most health deprived datazones in Scotland. At one extreme, 44.2% of datazones in Glasgow City and 36.8% in Inverclyde are within the 15% most deprived datazones in relation to health. By contrast, Orkney, Shetland, Eilean Siar, East Lothian and Moray have none of their datazones in the 15% most health deprived.


# Key data sources 

## Deprivation: key data sources 

A number of different measures of deprivation are in current use. This section provides an overview of sources of information on deprivation in general as well as showing where to access data for particular deprivation measures.

[Scottish Index of Multiple Deprivation (SIMD)](http://www.gov.scot/simd)

The most recent measure of deprivation is the Scottish Government's Scottish Index of Multiple Deprivation (SIMD). The latest version (SIMD 2016) was published in August 2016.  An interactive mapping tool is available [here](http://www.gov.scot/Topics/Statistics/SIMD/SIMDInteractive) and open access data can be found [here](http://statistics.gov.scot/data/scottish-index-of-multiple-deprivation-2016).

Data are also available for the SIMD 2004, 2006, 2009 and 2012.  [ISD Scotland](http://www.isdscotland.org/Products-and-Services/GPD-Support/Deprivation/SIMD/) have also published detailed look-up files for SIMD 2004, 2006, 2009, 2012 and 2016.

Arbuthnott Formula - ['Fair Shares for All'](http://www.isdscotland.org/Health-Topics/Finance/Resource-Allocation-Formula/)

The Arbuthnott formula was developed during 1999-2000 as part of a larger piece of work to update the calculations of health service resource allocation in Scotland. This formula uses a composite of four variables, one of which takes account of information from six other deprivation indicators. Three variables are drawn from 'updateable' sources (death rates, income support claimants and unemployment benefit recipients). The remaining variable is drawn from the 1991 Census. Unlike the Carstairs Score, lack of car ownership is not included. The Arbuthnott formula has been replaced by the NHSScotland Resource Allocation Committee (NRAC) forlmula, however, the basic structures of these formulae are very similar.

[Carstairs and Morris Index](https://www.gla.ac.uk/researchinstitutes/healthwellbeing/research/mrccsosocialandpublichealthsciencesunit/programmes/inequalities/healthinequalities/carstairsscores/)

The Carstairs and Morris Index index was originally developed in the 1980s using 1981 Census data and is updated using the most recent Census data. The index is derived from four Census indicators: low social class, lack of car ownership, overcrowding and male unemployment.  Carstairs Scores for Scottish Postcode Sectors, Datazones & Output Areas from the 2011 Census have now been published on Glasgow University's MRC Social and Public Health Sciences Unit (see link above). Note that the previous scores from 1981-2001 (at postcode level) can also be accessed there as well.

[Deprivation Profiles](http://www.isdscotland.org/Health-Topics/Public-Health/Publications/2015-12-08/2015-12-08-DeprivationProfiles-Summary.pdf)

Deprivation profiles, which provide data on health outcomes and determinants for each SIMD 2012 quintile (1=most deprived, 5=least least), for all health boards and local authorities within Scotland, are available in the [profiles pages](https://scotpho.nhsnss.scot.nhs.uk/scotpho/homeAction.do).

[Deprivation and health in Scotland (376 Kb)](https://www.scotpho.org.uk/downloads/deprivation/isd-deprivationreport-1998.pdf)

This 1998 report by ISD Scotland used routinely collected health service and mortality information to provide a brief overview of the relationship between material deprivation and ill health in Scotland at that time. Topic covered included mental health, heart disease, stroke and cancer.

[The Scottish Burden of Disease Study (2016) Deprivation Report](http://www.healthscotland.scot/health-inequalities/impact-of-ill-health/impact-of-deprivation-on-health)

The analysis used an internationally recognised approach, referred to as ‘Burden of Disease’, to quantify the difference between the ideal of living to old age in good health and the situation where healthy life is shortened by illness, injury, disability and early death.

[Dimensions of diversity: Population differences and health improvement opportunities](https://www.scotpho.org.uk/publications/reports-and-papers/dimensions-of-diversity-population-differences-and-health-improvement-opportunities/)

Published in 2010, this report provides a concise overview of basic information about 13 characteristics or groups of the population of Scotland, linking users to sources of further information. The distribution of each group is described in terms of their deprivation status.

[Family Resources Survey analyses of poverty](http://www.scotland.gov.uk/Topics/Statistics/Browse/Social-Welfare/IncomePoverty/CoreAnalysis#a2)

Detailed data on relative poverty in Scotland (by age, gender, ethnicity, urban-rural and SIMD classification) and inequality (using the Gini Coefficient), based on the Family Resources Survey is published by the Scottish Government.

[Local estimates of relative household poverty](https://www.gov.scot/Publications/2018/03/3017)

The Scottish Government have published estimates, based on national survey data, of the proportion of households in relative poverty at local authority level across Scotland.

**Local estimates of child poverty**

HM Revenue and Customs no longer publish local authority-level estimates of children living in income poverty.  [The last estimates of child income poverty published by HMRC relate to 2011](https://www.gov.uk/government/statistics/personal-tax-credits-children-in-low-income-families-local-measure).  Earlier estimates have been archived [here](http://webarchive.nationalarchives.gov.uk/20121103084242/http:/www.hmrc.gov.uk/stats/personal-tax-credits/child_poverty.htm). 

[End Child Poverty](http://www.endchildpoverty.org.uk/poverty-in-your-area-2016/) has used the same methodology and more recent data to estimate child poverty across the UK (including Scottish local authorities and parliamentary constituencies).  The latest estimates published relate to 2015.

[ISD Scotland - Deprivation]()

The main ISD Scotland site has a section on deprivation with useful pages with recommendations for analysing health data, ways to categorise deprivation variables and choices of geographical unit for small area analysis.

[Scottish Indices of Deprivation 2003](http://www.isdscotland.org/Products-and-Services/GPD-Support/Deprivation/)

The precursor to the SIMD were the Scottish Indices of Deprivation 2003, produced by Oxford University on behalf of the Scottish Executive. Similar to SIMD 2004, but using slightly different domains and indicators, this deprivation measure was calculated at electoral ward level. An overall index, domain-specific indices, report and maps are all available from the relevant page of the Scottish Executive web site (see link above).



# Key references and evidence

## Deprivation: key references and evidence

Bailey N, Flint J, Goodlad R, Shucksmith M, Fitzpatrick S, Pryce G. [Measuring Deprivation in Scotland: Developing a Long-Term Strategy Final Report](http://www.scotland.gov.uk/library5/social/mdis-00.asp). Glasgow: Scottish Centre for Research on Social Justice, Universities of Glasgow and Aberdeen 2003

Boyle P, Exeter D, Feng Z, Flowerdew R. [Suicide gap among young adults in Scotland: population study](http://bmj.bmjjournals.com/cgi/content/full/330/7484/175)
BMJ, January 22, 2005; 330(7484): 175 - 176.

Chalmers J, Capewell S. [Deprivation, disease, and death in Scotland: graphical display of survival of a cohort](http://bmj.bmjjournals.com/cgi/content/full/323/7319/967?maxtoshow=&HITS=10&hits=10&RESULTFORMAT=1&andorexacttitle=and&andorexacttitleabs=and&fulltext=deprivation+scotland&andorexactfulltext=and&searchid=1130520531860_13607&stored_search=&FIRSTIND) BMJ, Oct 2001; 323: 967 - 968.

Jarman B. [Underprivileged areas: validation and distribution of scores.](http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=retrieve&db=pubmed&list_uids=6439333&dopt=Abstract) BMJ 1984;289:1587-92.

Macintyre K, Stewart S, Chalmers J, Pell J, Finlayson A, Boyd J, Redpath A, McMurray J, Capewell S. [Relation between socioeconomic deprivation and death from a first myocardial infarction in Scotland: population based analysis](http://eprints.gla.ac.uk/74/). BMJ, May 2001; 322: 1152 - 1153

McAlister FA, Murphy NF, Simpson CR, Stewart S, MacIntyre K, Kirkpatrick M, Chalmers J, Redpath A, Capewell S, McMurray JJV. [Influence of socioeconomic deprivation on the primary care burden and treatment of patients with a diagnosis of heart failure in general practice in Scotland: population based study.](http://bmj.bmjjournals.com/cgi/content/full/328/7448/1110?maxtoshow=&HITS=10&hits=10&RESULTFORMAT=1&andorexacttitle=and&andorexacttitleabs=and&fulltext=deprivation+scotland&andorexactfulltext=and&searchid=1130520531860_13607&stored_search=&FIRSTIN) BMJ 2004;328:1110

McLeod A. [Changing patterns of teenage pregnancy: population based study of small areas](http://bmj.bmjjournals.com/cgi/content/full/323/7306/199?maxtoshow=&HITS=10&hits=10&RESULTFORMAT=1&title=Changing+patterns+of+teenage+pregnancy%3A+population+based+study+of+small+areas&andorexacttitle=and&andorexacttitleabs=and&andorexactfulltext=). BMJ, Jul 2001; 323: 199 - 203

McLoone P, Boddy FA. [Deprivation and mortality in Scotland, 1981 and 1991.](http://bmj.bmjjournals.com/cgi/content/full/309/6967/1465?maxtoshow=&HITS=10&hits=10&RESULTFORMAT=1&andorexacttitle=and&andorexacttitleabs=and&fulltext=deprivation+scotland&andorexactfulltext=and&searchid=1130520531860_13607&stored_search=&FIRSTIN) BMJ, Dec 1994; 309: 1465 - 1470.

Scottish Executive. [Inequalities in Health: Report of the Measuring Inequalities in Health Working Group.](http://www.scotland.gov.uk/Publications/2004/03/19045/34233) Edinburgh: Scottish Executive, 2004

Scottish Executive. [Social focus on deprived areas 2005.](http://www.scotland.gov.uk/Publications/2005/09/2792129/21311) Edinburgh: Scottish Executive, 2005

Scottish Executive. [Scottish Index of Multiple Deprivation 2006: General Report.](http://www.scotland.gov.uk/Publications/2006/10/13142739/0) Edinburgh: Scottish Executive, 2006.

Townsend P, Phillimore P, Beattie A. Health and deprivation: inequality and the North. London: Croom Helm, 1988.


## References 

## Effectiveness evidence

ScotPHO's purpose is to describe the pattern of health across the Scottish population. As a supplementary service to users, we include the following links to external sources of quality-assured evidence on effectiveness of interventions which may include relevant material for this topic. These links are provided as an aid to users. They are by no means exhaustive nor should they be necessarily viewed as authoritative.

[NHS Health Scotland: Scottish briefings on NICE public health guidance](http://www.healthscotland.com/scotlands-health/evidence/NICE.aspx)

[Centre for Reviews and Dissemination](http://www.york.ac.uk/crd/)

[Cochrane Library: Browse by topic](http://www.cochranelibrary.com/home/topic-and-review-group-list.html?page=topic)

[EPPI-Centre: Evidence library](http://eppi.ioe.ac.uk/cms/Default.aspx?tabid=56&language=en-US)

[National Institute for Health and Care Excellence (NICE) Evidence services: Evidence search](http://www.evidence.nhs.uk/)

[National Institute for Health and Care Excellence (NICE) Guidance: Find guidance](https://www.nice.org.uk/guidance)

[Scottish Intercollegiate Guidelines Network (SIGN)](http://www.sign.ac.uk/)

# Useful links 

## Deprivation: useful links 

[ISD Scotland - Deprivation](http://www.isdscotland.org/Products-and-Services/GPD-Support/Deprivation/SIMD/)

[MRC/CSO Social and Public Health Sciences Unit](http://www.gla.ac.uk/researchinstitutes/healthwellbeing/research/mrccsosocialandpublichealthsciencesunit/)

[Index of Multiple Deprivation for England (London example)](http://www.neighbourhood.statistics.gov.uk/dissemination/LeadDatasetList.do?a=7&b=276743&c=london&d=13&g=325264&i=1001x1003&m=0&enc=1&domainId=10)

[Poverty Alliance](http://www.povertyalliance.org/)

[Scottish Index of Multiple Deprivation (SIMD)](http://www.gov.scot/simd)

[Scottish Government - Social and Welfare - Income and Poverty Statistics](http://www.gov.scot/Topics/Statistics/Browse/Social-Welfare/IncomePoverty) 

[Scottish Neighbourhood Statistics](https://www.gov.scot/Topics/Statistics/sns/SNSRef)


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

